# Generated by Django 4.2.3 on 2023-08-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_evento_usuario_alter_evento_data_criacao_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="local_evento",
            field=models.CharField(
                default="local", max_length=100, verbose_name="Local do Evento"
            ),
        ),
    ]
